/**
 * Viral Metadata Generator Service
 * Generates titles, descriptions, tags, and hashtags for viral clips
 */

class ViralMetadataGenerator {
  constructor() {
    this.templates = {
      titles: [
        'You Won\'t Believe This Moment! 🤯',
        'The Most {emotion} Scene Ever! 😱',
        'Wait Until You See What Happens... 👀',
        'This Changed Everything! 🔥',
        'The Best {topic} Moment of {year}',
      ],
      hooks: [
        'Watch until the end!',
        'This is going viral!',
        'You need to see this!',
        'Mind = Blown 🤯',
      ],
    };
  }

  generateMetadata(videoInfo, clipData) {
    const { title, duration, score } = clipData;
    
    return {
      title: this.generateTitle(videoInfo, clipData),
      description: this.generateDescription(videoInfo, clipData),
      tags: this.generateTags(videoInfo),
      hashtags: this.generateHashtags(score),
    };
  }

  generateTitle(videoInfo, clipData) {
    const templates = this.templates.titles;
    const template = templates[Math.floor(Math.random() * templates.length)];
    
    return template
      .replace('{emotion}', 'Epic')
      .replace('{topic}', videoInfo?.topic || 'Video')
      .replace('{year}', new Date().getFullYear());
  }

  generateDescription(videoInfo, clipData) {
    const hooks = this.templates.hooks;
    const randomHook = hooks[Math.floor(Math.random() * hooks.length)];
    
    return `${randomHook}\n\n${videoInfo?.title || 'Viral Moment'} - \nThis clip was automatically generated by GravityClaw.\n\n${this.generateHashtags(clipData.score).join(' ')}`;
  }

  generateTags(videoInfo) {
    const baseTags = ['viral', 'trending', 'fyp', 'shorts', 'tiktok', 'reels'];
    const customTags = videoInfo?.tags || [];
    return [...baseTags, ...customTags].slice(0, 15);
  }

  generateHashtags(viralScore) {
    const hashtags = ['#viral', '#trending', '#fyp'];
    
    if (viralScore >= 0.8) {
      hashtags.push('#mustwatch', '#epic');
    } else if (viralScore >= 0.6) {
      hashtags.push('#amazing', '#wow');
    }
    
    hashtags.push('#shorts', '#tiktok', '#reels', '#youtube');
    
    return hashtags;
  }
}

module.exports = ViralMetadataGenerator;
